In [1]:
import numpy as np

In [2]:
# Crea un array 1D con 50 valores aleatorio del 10 al 99. Accede a los elementos en las posiciones múltiplos de 5.
array_1D =np.random.randint (10, 100,size=50)

In [3]:
array_1D

array([87, 76, 58, 79, 72, 24, 47, 69, 56, 76, 21, 68, 63, 67, 47, 14, 90,
       40, 51, 92, 18, 40, 95, 20, 17, 88, 39, 33, 55, 59, 50, 77, 33, 42,
       13, 13, 11, 19, 34, 21, 52, 61, 98, 66, 85, 22, 69, 82, 15, 60],
      dtype=int32)

In [4]:
#Accede a los elementos en las posiciones múltiplos de 5.
array_1D [::5]

array([87, 24, 21, 14, 18, 88, 50, 13, 52, 22], dtype=int32)

In [5]:
#Crea un array 1D con 30 valores aleatorios del 1 al 20 (ambos incluidos). Utiliza indexación para obtener los elementos en las posiciones impares.
array_1D_2 =np.random.randint (1, 21,size=30)

In [6]:
array_1D_2

array([ 6, 16, 18, 17, 17,  8, 20,  4,  9,  9, 15, 11, 12,  9, 14, 16,  2,
        1,  8, 17, 18, 10,  9, 16,  5,  2, 13, 18,  6,  7], dtype=int32)

In [7]:
array_1D_2[1::2]

array([16, 17,  8,  4,  9, 11,  9, 16,  1, 17, 10, 16,  2, 18,  7],
      dtype=int32)

In [8]:
#Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar comprendidos solo entre 0 y 1). 

In [9]:
a=np.random.rand (4,6)
print(a)

[[0.6833897  0.59559716 0.78087699 0.94515717 0.2545111  0.61248215]
 [0.13843309 0.8725672  0.4452142  0.43184321 0.82729184 0.26373966]
 [0.51752224 0.809519   0.4199004  0.77462798 0.20925248 0.28610668]
 [0.00595197 0.60615299 0.16769593 0.49032293 0.32493691 0.32944322]]


In [10]:
b=np.random.randint(1,20,(4,6))
print(b)

[[12  4 18 15 11  7]
 [ 2 10  7  3 10  2]
 [14 10  2  4  7  8]
 [12  6  8 10  3  4]]


In [11]:
array_2D=a+b
print(array_2D)

[[12.6833897   4.59559716 18.78087699 15.94515717 11.2545111   7.61248215]
 [ 2.13843309 10.8725672   7.4452142   3.43184321 10.82729184  2.26373966]
 [14.51752224 10.809519    2.4199004   4.77462798  7.20925248  8.28610668]
 [12.00595197  6.60615299  8.16769593 10.49032293  3.32493691  4.32944322]]


In [12]:
# Accede a la última fila de la matriz. Los decimales deben estar redondeados a 2 decimales.

In [14]:
ultima_fila = np.round(array_2D[-1], 2)

In [15]:
print(ultima_fila)

[12.01  6.61  8.17 10.49  3.32  4.33]
