In [1]:
import pandas as pd
import numpy as np

¿Qué diferencia hay entre una Serie y un DataFrame?
-Las columnas de un dataframe son series.Un dataframe tiene forma de tabla y una serie es una columna en una tabla
-Un dataframe es bidimensional (2 variables) las series son unidimensionales (una variable)

In [2]:
# Crea un array de dos dimensiones con 4 filas y 3 columnas.
array_2d = np.random.randint(1, 10,(4, 3))
print(array_2d)

[[3 7 2]
 [5 7 5]
 [8 3 5]
 [5 9 3]]


In [3]:
#Convierte el array en un DataFrame donde las columnas se llamen "España", "Francia" e "Italia".
df = pd.DataFrame(array_2d, columns=["España", "Francia", "Italia"])
print(df)

   España  Francia  Italia
0       3        7       2
1       5        7       5
2       8        3       5
3       5        9       3


In [4]:
# Descarga el archivo "medallas" y carga el DataFrame.
medallas = pd.read_csv("file/medallas.csv", index_col=0)

In [5]:
medallas

País   Oro  Plata  Bronce
1             China  1473    994     720
2             Japón  1032   1037     985
3     Corea del Sur   745    663     827
4              Irán   179    181     197
5        Kazajistán   155    158     224
6             India   154    202     315
7         Tailandia   132    175     278
8         Indonesia   112    131     240
9      China Taipéi    99    144     276
10  Corea del Norte    91    120     235

In [15]:
#Usando el loc extrae todas las columnas de la fila de Tailandia
fila_tailandia = medallas.loc[7]
fila_tailandia

País      Tailandia
Oro             132
Plata           175
Bronce          278
Name: 7, dtype: object

In [ ]:

filas_china_iran = medallas.loc[[1, 4]]
filas_china_iran

País   Oro  Plata  Bronce
1  China  1473    994     720
4   Irán   179    181     197